apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: mlops-infrastructure
  namespace: infrastructure
  title: ML Ops Infrastructure
  description: |
    Deployed infrastructure for ML Ops
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: canal-consulting/mlops-infrastructure
spec:
  domain: infrastructure
  owner: ml-ops

